stages:
  - build
  - test
  - deploy
  - status

.manual_template:
  when: manual

.build_template:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - sh maintainer/docker_build.sh
  tags:
    - docker
    - linux
    - nofirewall

.deploy_template:
  extends: .build_template
  stage: deploy
  only:
    - master

.test_template:
  stage: test
  image: $CI_REGISTRY/$CI_PROJECT_PATH/$CI_JOB_NAME-$CI_COMMIT_SHA
  script:
    - git clone --depth=1 --recursive https://github.com/espressomd/espresso
    - cd espresso
    - maintainer/CI/build_cmake.sh
  variables:
    make_check: "false"
    myconfig: "maxset"
  tags:
    - docker
    - linux

centos-python3:7:build:
  extends: .build_template
centos-python3:next:build:
  extends: .build_template
debian-python3:9:build:
  extends: .build_template
opensuse:15.1:build:
  extends: .build_template
ubuntu-python3:wo-dependencies:build:
  extends: .build_template
clang-python3:6.0:build:
  extends: .build_template
cuda:tutorials:build:
  extends: .build_template
cuda:9.0:build:
  extends: .build_template
rocm-python3:latest:build:
  extends: .build_template
intel-python3:18:build:
  extends:
    - .build_template
    - .manual_template
  tags:
    - docker
    - linux
    - nofirewall
    - icp
ubuntu-python3:18.04:build:
  extends: .build_template
ubuntu-python3:wo-dependencies:build:
  extends: .build_template
ubuntu-python3:min_boost:build:
  extends: .build_template
ubuntu:arm64:build:
  extends:
    - .build_template
    - .manual_template
ubuntu:armhf:build:
  extends:
    - .build_template
    - .manual_template
ubuntu:i386:build:
  extends:
    - .build_template
    - .manual_template
ubuntu:ppc64le:build:
  extends:
    - .build_template
    - .manual_template
ubuntu:s390x:build:
  extends:
    - .build_template
    - .manual_template

test/centos-python3:7:
  extends: .test_template
test/centos-python3:next:
  extends: .test_template
test/debian-python3:9:
  extends: .test_template
test/opensuse:15.1:
  extends: .test_template
test/clang-python3:6.0:
  extends: .test_template
test/cuda:tutorials:
  extends: .test_template
test/cuda:9.0:
  extends: .test_template
test/rocm-python3:latest:
  extends: .test_template
  variables:
    make_check: "false"
    myconfig: "maxset"
    HIP_PLATFORM: "hcc"
    HCC_AMDGPU_TARGET: "gfx900"
test/intel-python3:18:
  extends:
    - .test_template
    - .manual_template
  tags:
    - docker
    - linux
    - icp
test/ubuntu-python3:18.04:
  extends: .test_template
test/ubuntu-python3:min_boost:
  extends: .test_template
test/ubuntu:arm64:
  extends:
    - .test_template
    - .manual_template
test/ubuntu:armhf:
  extends:
    - .test_template
    - .manual_template
test/ubuntu:i386:
  extends:
    - .test_template
    - .manual_template
test/ubuntu:ppc64le:
  extends:
    - .test_template
    - .manual_template
test/ubuntu:s390x:
  extends:
    - .test_template
    - .manual_template
test/ubuntu-python3:wo-dependencies:
  extends: .test_template


centos-python3:7:
  extends: .deploy_template
centos-python3:next:
  extends: .deploy_template
debian-python3:9:
  extends: .deploy_template
opensuse:15.1:
  extends: .deploy_template
clang-python3:6.0:
  extends: .deploy_template
cuda:tutorials:
  extends: .deploy_template
cuda:9.0:
  extends: .deploy_template
rocm-python3:latest:
  extends: .deploy_template
intel-python3:18:
  extends:
    - .deploy_template
    - .manual_template
  tags:
    - docker
    - linux
    - nofirewall
    - icp
ubuntu-python3:18.04:
  extends: .deploy_template
ubuntu-python3:wo-dependencies:
  extends: .deploy_template
ubuntu-python3:min_boost:
  extends: .deploy_template
ubuntu:arm64:
  extends:
    - .deploy_template
    - .manual_template
ubuntu:armhf:
  extends:
    - .deploy_template
    - .manual_template
ubuntu:i386:
  extends:
    - .deploy_template
    - .manual_template
ubuntu:ppc64le:
  extends:
    - .deploy_template
    - .manual_template
ubuntu:s390x:
  extends:
    - .deploy_template
    - .manual_template

status_success:
  stage: status
  image: $CI_REGISTRY/espressomd/docker/ubuntu-python3:18.04
  script: bash maintainer/gh_post_status.sh success
  when: on_success
  tags:
    - linux

status_failure:
  stage: status
  image: $CI_REGISTRY/espressomd/docker/ubuntu-python3:18.04
  script: bash maintainer/gh_post_status.sh failure
  when: on_failure
  tags:
    - linux
