image: docker:latest
services:
  - docker:dind

.build_template: &build_definition
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd docker/$CI_JOB_NAME
    - docker pull $CI_REGISTRY/$CI_PROJECT_PATH/$CI_JOB_NAME:latest || true
    - docker build --pull -t $CI_REGISTRY/$CI_PROJECT_PATH/$CI_JOB_NAME:latest --cache-from $CI_REGISTRY/$CI_PROJECT_PATH/$CI_JOB_NAME:latest .
    - test "$CI_COMMIT_REF_NAME" != "master" || docker push $CI_REGISTRY/$CI_PROJECT_PATH/$CI_JOB_NAME:latest
  tags:
    - docker
    - privileged

centos:
  <<: *build_definition
debian:
  <<: *build_definition
opensuse:
  <<: *build_definition
ubuntu:
  <<: *build_definition
ubuntu-clang-cuda:
  <<: *build_definition
ubuntu-cuda:
  <<: *build_definition
ubuntu-intel:
  <<: *build_definition
ubuntu-python3:
  <<: *build_definition
