sudo: required
services:
  - docker
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

jobs:
  include:
    - script: bash test/build_docker_images.sh centos
    - script: bash test/build_docker_images.sh debian
    - script: bash test/build_docker_images.sh opensuse
    - script: bash test/build_docker_images.sh ubuntu
    - script: bash test/build_docker_images.sh ubuntu-clang-cuda
    - script: bash test/build_docker_images.sh ubuntu-cuda
    - script: bash test/build_docker_images.sh ubuntu-python3
