name: Docker images

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' 

jobs:
  images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['centos', 'clang', 'debian', 'fedora', 'opensuse', 'rocm',
                'ubuntu-18.04', 'ubuntu-19.04', 'ubuntu-cuda-10.1', 'ubuntu-cuda-9.0',
                'ubuntu-min_boost', 'ubuntu-travis', 'ubuntu-wo-dependencies']
    steps:
    - uses: actions/checkout@master
    - name: Build and deploy
      uses: ./.github/actions/docker
      with:
        image: ${{ matrix.image }}
        repository: ${{ github.repository }}
        password: ${{ secrets.GITHUB_TOKEN }}
        event_name: ${{ github.event_name }}
        tag: ${{ github.sha }}
